/*
Encodes and decodes URI strings for QR code payloads.

Formats:
  iou://friend?key=npub1...&name=Alice&relay=wss://relay1.com&relay=wss://relay2.com
  iou://pay?key=npub1...&amount=50&note=lunch

The `friend` URI embeds the user's display name and relay URLs so a scanner
can show a human-readable name for the pending request and, in a future step,
auto-suggest compatible relay servers.  All fields beyond `key` are optional so
URIs generated by older app versions remain scannable.
*/

export const encodeAddFriendUri = (npub, { name, relays = [] } = {}) => {
  const params = new URLSearchParams({ key: npub });
  if (name) params.set("name", name);
  relays.forEach((url) => params.append("relay", url));
  return `iou://friend?${params}`;
};

export const encodePayUri = (npub, amount, note) => {
  const params = new URLSearchParams({ key: npub });
  if (amount) params.set("amount", String(amount));
  if (note) params.set("note", note);
  return `iou://pay?${params}`;
};

export const parseIouUri = (text) => {
  const trimmed = typeof text === "string" ? text.trim() : "";
  if (!trimmed.startsWith("iou://")) return null;

  try {
    // Replace iou:// with https:// so URL parser works
    const url = new URL(trimmed.replace("iou://", "https://"));
    const type = url.hostname;
    if (type !== "friend" && type !== "pay") return null;

    const key = url.searchParams.get("key") || "";
    if (!key) return null;

    const result = { type, key };

    if (type === "friend") {
      const name = url.searchParams.get("name");
      if (name) result.name = name;
      const relays = url.searchParams.getAll("relay").filter(Boolean);
      if (relays.length) result.relays = relays;
    }

    if (type === "pay") {
      const amount = url.searchParams.get("amount");
      if (amount) result.amount = parseFloat(amount);
      const note = url.searchParams.get("note");
      if (note) result.note = note;
    }

    return result;
  } catch {
    return null;
  }
};
